_target_: ascent.models.components.transunet.VisionTransformer
img_size: [128,128]
in_channels: 1
num_classes: 4
patch_size_: 8
patches_grid: [8, 8]
hidden_size: 768
resnet_num_layers: [3, 4, 9]
resnet_width_factor: 1
dropout_rate: 0.1
transformer_num_layers: 12
transformer_mlp_dim: 3072
transformer_dropout_rate: 0.1
transformer_num_heads: 12
transformer_attention_dropout_rate: 0.0
n_skip: 3
skip_channels: [512, 256, 64, 16]
classifier: "seg"
decoder_channels: [256, 128, 64, 16]
zero_head: False
vis: False
pretrained_path: "/home/deleat/Documents/RomainD/Working_space/NN_models/training_LLDM_v2/training_transUnet/R50+ViT-B_16.npz"
