_target_: ascent.models.components.unetr_pp.UNETR_PP
in_channels: 1
num_classes: 4
patch_size_: [128, 128]
feature_size: 16
feature_size_multiplier: [2, 4, 8, 16]
depths: [3, 3, 3, 3]
kernel_size: [[4, 4], [2, 2], [2, 2], [2, 2]]
stride: [[4, 4], [2, 2], [2, 2], [2, 2]]
proj_feat_size: [4, 4]
num_heads: 4
pos_embed: perceptron
norm_name: instance
dropout_rate: 0.1
deep_supervision: True