defaults:
  - net: transunet
  - optimizer: sgd
  - scheduler: polylr
  - scheduler_config: default
  - loss: dice_ce

_target_: ascent.models.transunet_module.TransUNetLitModule

tta: True
save_predictions: True
save_npz: False
name: TransUNet
