defaults:
  - net: unetr
  - optimizer: sgd
  - scheduler: polylr
  - scheduler_config: default
  - loss: dice_ce

_target_: ascent.models.unetr_module.UNetRLitModule

tta: True
save_predictions: True
save_npz: False
name: UNetR
